#!/usr/bin/env node
// Regenerates migrations/0002_seed_generators.sql from the repo registration CSV.
// Mirrors the legacy api/scrape/nem_registration.js logic: one generator per
// (station name, DUID) pair, first row wins for metadata, reg/max capacities
// summed across physical-unit rows, '-' capacities ignored. Two deliberate
// departures from legacy: the reg_cap/max_cap swap bug on first insert is fixed,
// and the 'unknown' sentinel generator row is not emitted.
import { readFileSync, writeFileSync } from 'node:fs';
import assert from 'node:assert/strict';

const CSV_PATH = new URL('../../api/db/files/nem_registration_latest.csv', import.meta.url);
const OUT_PATH = new URL('../migrations/0002_seed_generators.sql', import.meta.url);

// RFC 4180-ish: quoted fields, "" escapes a quote, \r\n or \n row endings.
function parseCsv(text) {
  const rows = [];
  let row = [], field = '', inQuotes = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (inQuotes) {
      if (c === '"') {
        if (text[i + 1] === '"') { field += '"'; i++; } else { inQuotes = false; }
      } else { field += c; }
    } else if (c === '"') {
      inQuotes = true;
    } else if (c === ',') {
      row.push(field); field = '';
    } else if (c === '\n' || c === '\r') {
      if (c === '\r' && text[i + 1] === '\n') i++;
      row.push(field); field = '';
      if (row.length > 1 || row[0] !== '') rows.push(row);
      row = [];
    } else { field += c; }
  }
  if (field !== '' || row.length) { row.push(field); rows.push(row); }
  return rows;
}

function collapseGenerators(rows) {
  const byKey = new Map(); // "name\0duid" -> generator
  for (const r of rows) {
    const name = r[1].trim(), state = r[2].trim(), duid = r[13].trim();
    const reg = Number(r[14].trim()), max = Number(r[15].trim()); // '-' -> NaN
    const key = `${name}\0${duid}`;
    const existing = byKey.get(key);
    if (!existing) {
      byKey.set(key, {
        name,
        participant_name: r[0].trim(),
        duid,
        state,
        technology_type: r[8].trim(),
        technology_description: r[9].trim(),
        fuel_type: r[6].trim(),
        fuel_description: r[7].trim(),
        reg_cap: Number.isNaN(reg) ? 0 : reg,
        max_cap: Number.isNaN(max) ? 0 : max,
      });
    } else {
      if (!Number.isNaN(reg)) existing.reg_cap += reg;
      if (!Number.isNaN(max)) existing.max_cap += max;
    }
  }
  return [...byKey.values()];
}

const sq = (s) => `'${s.replaceAll("'", "''")}'`;
// Round float-sum artifacts (e.g. 0.1+0.2) to 6dp; capacities are MW with ≤2dp in source.
const num = (n) => String(Math.round(n * 1e6) / 1e6);

function selfCheck() {
  assert.deepEqual(
    parseCsv('a,"b, ""x""",c\r\nd,e,f\n'),
    [['a', 'b, "x"', 'c'], ['d', 'e', 'f']],
    'CSV parser broke on quotes/CRLF',
  );
  const rows = [
    ['P1', 'Station A', 'VIC1', '', '', '', 'Hydro', 'Water', 'Renewable', 'Gravity', '', '', '', 'DUID1', '10.5', '20', ''],
    ['P2', 'Station A', 'NSW1', '', '', '', 'Coal', 'Black', 'Fossil', 'Steam', '', '', '', 'DUID1', '-', '5', ''],
  ];
  const [g] = collapseGenerators(rows);
  assert.equal(collapseGenerators(rows).length, 1, 'dedup by (name,duid) broke');
  assert.equal(g.reg_cap, 10.5, "'-' capacity must not corrupt the sum");
  assert.equal(g.max_cap, 25, 'capacity summing broke');
  assert.equal(g.participant_name, 'P1', 'first row must win for metadata');
  assert.equal(sq("O'Brien"), "'O''Brien'", 'SQL escaping broke');
}

selfCheck();

const csvRows = parseCsv(readFileSync(CSV_PATH, 'utf-8'));
const header = csvRows.shift();
assert.equal(header[13].trim(), 'DUID', `unexpected CSV layout: column 13 is ${header[13]}`);
const generators = collapseGenerators(csvRows);
assert.ok(generators.length > 0, 'no generators parsed');

const values = generators.map((g) =>
  `(${[g.name, g.participant_name, g.duid, g.state, g.technology_type, g.technology_description, g.fuel_type, g.fuel_description]
    .map(sq).join(',')},${num(g.reg_cap)},${num(g.max_cap)})`,
);

const batches = [];
for (let i = 0; i < values.length; i += 50) {
  batches.push(
    'INSERT INTO generators (name,participant_name,duid,state,technology_type,technology_description,fuel_type,fuel_description,reg_cap,max_cap) VALUES\n'
    + values.slice(i, i + 50).join(',\n') + ';',
  );
}

writeFileSync(OUT_PATH, `-- GENERATED by scripts/generate-seed.mjs — do not edit by hand.
-- Source: api/db/files/nem_registration_latest.csv (${csvRows.length} unit rows -> ${generators.length} generators).
DELETE FROM generators;
${batches.join('\n')}
`);

console.log(`Wrote ${generators.length} generators (from ${csvRows.length} CSV unit rows) to migrations/0002_seed_generators.sql`);
